---
sudo: required
language: python
services:
  - docker

env:
  global:
    - DNS_SERVER1: 1.1.1.1
    - DNS_SERVER2: 8.8.8.8

before_install:
  - sudo apt-get -qq update

install:
  - pip install molecule docker-py

script:
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
