---
- name: Install GPG packages
  apt:
    name:
      - gnupg
      - apt-transport-https
    state: present
    update_cache: true
  become: true
  register: apt_result
  until: apt_result is success
  retries: 10
  delay: 2

- name: Import APT GPG keys
  apt_key:
    url: "{{ item.url }}"
    state: present
    keyring: "{{ item.keyring_path }}/{{ item.file }}"
  with_items:
    - "{{ repository_deb_nsls }}"
  become: true

- name: Add default repositories
  apt_repository:
    repo: "{{ item.baseurl }}"
    state: "{{ item.state }}"
    filename: "{{ item.file }}"
    update_cache: true
  with_items:
    - "{{ repository_apt_baseurl }}"
  become: true
