---
dependency:
  name: galaxy
lint:
  name: yamllint
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      default_group:
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
driver:
  name: docker
platforms:
  - name: lnls-ans-role-repository-debian-jessie
    image: debian:jessie
    groups:
      - default_group
    dns_servers:
      - 10.0.0.71
      - 10.0.0.72
  - name: lnls-ans-role-repository-debian-stretch
    image: debian:stretch
    groups:
      - default_group
    dns_servers:
      - 10.0.0.71
      - 10.0.0.72
  - name: lnls-ans-role-repository-ubuntu-trusty
    image: ubuntu:trusty
    groups:
      - default_group
    dns_servers:
      - 10.0.0.71
      - 10.0.0.72
  - name: lnls-ans-role-repository-ubuntu-xenial
    image: ubuntu:xenial
    groups:
      - default_group
    dns_servers:
      - 10.0.0.71
      - 10.0.0.72
